### ISSUE TITLE
你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案

### ISSUE THREAD

**Issue by zhangtaokd** [CCChenhao997/DualGCN-ABSA#2]
```
choice cuda:0
Training examples:   0%|          | 0/2282 [00:00<?, ?it/s]Loading model from ../LAL-Parser/best_model/best_parser.pt...
Training examples:   0%|          | 0/2282 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "D:\Anaconda\envs\dugcn\lib\site-packages\transformers\tokenization_utils_base.py", line 1572, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\Anaconda\envs\dugcn\lib\site-packages\transformers\tokenization_xlnet.py", line 158, in __init__
    self.sp_model.Load(vocab_file)
  File "D:\Anaconda\envs\dugcn\lib\site-packages\sentencepiece\__init__.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "D:\Anaconda\envs\dugcn\lib\site-packages\sentencepiece\__init__.py", line 171, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "C:\Users\211实验室/.cache\torch\transformers\5b125ba222ff82664771f63cd8fac9696c24b403fc1ab720d537fe2ceaaf0576.8b10bd978b5d01c21303cc761fc9ecd464419b3bf921864a355ba807cfbfafa8": Illegal byte sequence Error #42

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pycharm_project/DualGCN-ABSA-main/DualGCN/train.py", line 388, in <module>
    main()
  File "D:/pycharm_project/DualGCN-ABSA-main/DualGCN/train.py", line 384, in main
    ins = Instructor(opt)
  File "D:/pycharm_project/DualGCN-ABSA-main/DualGCN/train.py", line 50, in __init__
    trainset = ABSAGCNData(opt.dataset_file['train'], tokenizer, opt=opt)
  File "D:\pycharm_project\DualGCN-ABSA-main\DualGCN\data_utils.py", line 325, in __init__
    from absa_parser import headparser
  File "D:\pycharm_project\DualGCN-ABSA-main\DualGCN\../LAL-Parser/src_joint\absa_parser.py", line 49, in <module>
    headparser = ParseHead(config)
  File "D:\pycharm_project\DualGCN-ABSA-main\DualGCN\../LAL-Parser/src_joint\absa_parser.py", line 33, in __init__
    self.parser = KM_parser.ChartParser.from_spec(info['spec'], info['state_dict'])
  File "D:\pycharm_project\DualGCN-ABSA-main\DualGCN\../LAL-Parser/src_joint\KM_parser.py", line 1452, in from_spec
    res = cls(**spec)
  File "D:\pycharm_project\DualGCN-ABSA-main\DualGCN\../LAL-Parser/src_joint\KM_parser.py", line 1282, in __init__
    self.xlnet_tokenizer, self.xlnet = get_xlnet(hparams.xlnet_model, hparams.xlnet_do_lower_case)
  File "D:\pycharm_project\DualGCN-ABSA-main\DualGCN\../LAL-Parser/src_joint\KM_parser.py", line 699, in get_xlnet
    tokenizer = XLNetTokenizer.from_pretrained(xlnet_model, do_lower_case=xlnet_do_lower_case)
  File "D:\Anaconda\envs\dugcn\lib\site-packages\transformers\tokenization_utils_base.py", line 1425, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "D:\Anaconda\envs\dugcn\lib\site-packages\transformers\tokenization_utils_base.py", line 1574, in _from_pretrained
    raise OSError(
OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted
```.

**Comment by StudentWorker** [comment]
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte
我是卡在了这一步，解决了吗？

**Comment by zhangtaokd** [comment]
我换服务器跑的，现在能跑通了，但是实验效果差好多



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月28日(星期天) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)





 (result, consumed) = self._buffer_decode(data, self.errors, final)  
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte
 我是卡在了这一步，解决了吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
换在线下载已经解决这个问题了，但是又出了另一个问题


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月30日 15:16:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)




 我换服务器跑的，现在能跑通了，但是实验效果差好多 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年11月28日(星期天) 晚上9:22 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
 
  (result, consumed) = self._buffer_decode(data, self.errors, final)   
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte 
  我是卡在了这一步，解决了吗？ 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
说是需要long但传入的是iny脑壳疼


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月30日 15:16:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)




 我换服务器跑的，现在能跑通了，但是实验效果差好多 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年11月28日(星期天) 晚上9:22 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
 
  (result, consumed) = self._buffer_decode(data, self.errors, final)   
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte 
  我是卡在了这一步，解决了吗？ 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
我已经放弃，打算从bert重跑。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月30日 15:16:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)




 我换服务器跑的，现在能跑通了，但是实验效果差好多 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年11月28日(星期天) 晚上9:22 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
 
  (result, consumed) = self._buffer_decode(data, self.errors, final)   
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte 
  我是卡在了这一步，解决了吗？ 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangtaokd** [comment]
换一个吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCChenhao997/DualGCN-ABSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 晚上7:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)





 我已经放弃，打算从bert重跑。 
 
 
   
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年11月30日 15:16:49 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
  我换服务器跑的，现在能跑通了，但是实验效果差好多  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年11月28日(星期天) 晚上9:22  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)  
   
   
   
   
   
   (result, consumed) = self._buffer_decode(data, self.errors, final)    
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte  
   我是卡在了这一步，解决了吗？  
     
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
你也放弃了？


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月30日 20:11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)




 换一个吧 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CCChenhao997/DualGCN-ABSA"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月30日(星期二) 晚上7:47 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
 
  我已经放弃，打算从bert重跑。  
   
   
     
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年11月30日 15:16:49  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)  
   
   
   
   
   我换服务器跑的，现在能跑通了，但是实验效果差好多   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2021年11月28日(星期天) 晚上9:22   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)   
     
     
     
     
     
    (result, consumed) = self._buffer_decode(data, self.errors, final)     
   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte   
    我是卡在了这一步，解决了吗？   
       
   —   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangtaokd** [comment]
我跑通了啊，放啥弃


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCChenhao997/DualGCN-ABSA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)





 你也放弃了？ 
 
 
   
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年11月30日 20:11:07 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
  换一个吧  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "CCChenhao997/DualGCN-ABSA"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月30日(星期二) 晚上7:47  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)  
   
   
   
   
   
   我已经放弃，打算从bert重跑。   
     
     
       
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年11月30日 15:16:49   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)   
     
     
     
     
    我换服务器跑的，现在能跑通了，但是实验效果差好多    
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: ***@***.***&amp;amp;amp;amp;gt;;     
    发送时间: 2021年11月28日(星期天) 晚上9:22    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;     
    抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;;     
    主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)    
       
       
       
       
       
     (result, consumed) = self._buffer_decode(data, self.errors, final)      
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte    
     我是卡在了这一步，解决了吗？    
         
    —    
    You are receiving this because you authored the thread.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StudentWorker** [comment]
你不是实验结果差很多么。。。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月30日 20:14:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)




 我跑通了啊，放啥弃 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CCChenhao997/DualGCN-ABSA"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月30日(星期二) 晚上8:11 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 
 
 
 
 
 
  你也放弃了？  
   
   
     
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年11月30日 20:11:07  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)  
   
   
   
   
   换一个吧   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "CCChenhao997/DualGCN-ABSA"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年11月30日(星期二) 晚上7:47   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)   
     
     
     
     
     
    我已经放弃，打算从bert重跑。    
       
       
         
    ---原始邮件---    
    发件人: ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2021年11月30日 15:16:49    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;    
    抄送: ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)    
       
       
       
       
     我换服务器跑的，现在能跑通了，但是实验效果差好多     
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人: ***@***.***&amp;amp;amp;amp;amp;gt;;      
     发送时间: 2021年11月28日(星期天) 晚上9:22     
     收件人: ***@***.***&amp;amp;amp;amp;amp;gt;;      
     抄送: ***@***.***&amp;amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;amp;gt;;      
     主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2)     
         
         
         
         
         
      (result, consumed) = self._buffer_decode(data, self.errors, final)       
     UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte     
      我是卡在了这一步，解决了吗？     
           
     —     
     You are receiving this because you authored the thread.     
     Reply to this email directly, view it on GitHub, or unsubscribe.     
     Triage notifications on the go with GitHub Mobile for iOS or Android.     
    —    
    You are receiving this because you commented.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Healer10086** [comment]
> 我跑通了啊，放啥弃
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CCChenhao997/DualGCN-ABSA" ***@***.***&gt;; 发送时间:&nbsp;2021年11月30日(星期二) 晚上8:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 你也放弃了？
> ---原始邮件--- 发件人: ***@***.***&amp;gt; 发送时间: 2021年11月30日 20:11:07 收件人: ***@***.***&amp;gt;; 抄送: ***@***.******@***.***&amp;gt;; 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 换一个吧
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "CCChenhao997/DualGCN-ABSA" ***@***.***&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2021年11月30日(星期二) 晚上7:47 ***@***.***&amp;amp;gt;; ***@***.******@***.***&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 我已经放弃，打算从bert重跑。
> ---原始邮件--- 发件人: ***@***.***&amp;amp;amp;gt; 发送时间: 2021年11月30日 15:16:49 收件人: ***@***.***&amp;amp;amp;gt;; 抄送: ***@***.******@***.***&amp;amp;amp;gt;; 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) 我换服务器跑的，现在能跑通了，但是实验效果差好多
> ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------ 发件人: ***@***.***&amp;amp;amp;amp;gt;; 发送时间: 2021年11月28日(星期天) 晚上9:22 收件人: ***@***.***&amp;amp;amp;amp;gt;; 抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;; 主题: Re: [CCChenhao997/DualGCN-ABSA] 你好！我在windows上跑您代码的时候，出现了以下错误，请问该怎么解决，环境我按照您给的配置好了，但是依然有Bug，在网上也没有搜到解决方案 (#2) (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 254: invalid start byte 我是卡在了这一步，解决了吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

大佬你好，请问你可以分享下best_parser.pt这个文件吗，分享链接已经失效了，谷歌云盘我又没权限
